### ISSUE TITLE
RESTer throws errors when sending queries

### ISSUE THREAD

**Issue by pwetosaurus** [frigus02/RESTer#1]
Trying to make some queries, on firefox 42.0 on Ubuntu 15.10, nothing append when using the SEND button, and the console throws the following error :

Error: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.
createTransaction@resource://rester-at-kuehle-dot-me/data/site/scripts/services/data.js:411:31
self.getHistoryEntries/<@resource://rester-at-kuehle-dot-me/data/site/scripts/services/data.js:216:1
f/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:118:334
hf/this.$get</n.prototype.$eval@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:132:448
hf/this.$get</n.prototype.$digest@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:129:455
hf/this.$get</n.prototype.$evalAsync/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:133:30
e@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:43:93
Hf/l.defer/c<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:45:491

**Comment by frigus02** [comment]
@pwetosaurus Thanks for reporting. This bug is already fixed in the latest version [1.2.1](https://addons.mozilla.org/de/firefox/addon/rester/versions/1.2.1). I'm waiting for more than a week now for the review of this version.

**Comment by frigus02** [comment]
The update has just been reviewed. Can you confirm, that this fixes your bug?

**Comment by pwetosaurus** [comment]
I will check that on monday, at work, where thé RESTer module is installés.
Thanks a lot. :)

**Comment by pwetosaurus** [comment]
Where the RESTer module ils installed* (bad, bad french mobile spell
checker)

**Comment by pwetosaurus** [comment]
This issue doesn't seems to be resolved with the 1.2.1 (Neither after update, nor firefox restart or uninstall and reinstall of the RESTer module.

At startup two errors still occurs refering to — apparently — the same problem of — apparently again — missing database access.

Are there some prerequisite to the use of the extension ? I just install it and try to use it directly, assuming that the README.md instruction were relevant for the developement of the extension and not for a simple usage of the RESTer extension.

_Error: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.
createTransaction@resource://rester-at-kuehle-dot-me/data/site/scripts/services/data.js:411:31
self.getRequests/<@resource://rester-at-kuehle-dot-me/data/site/scripts/services/data.js:77:1
f/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:118:334
hf/this.$get</n.prototype.$eval@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:132:448
hf/this.$get</n.prototype.$digest@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:129:455
hf/this.$get</n.prototype.$evalAsync/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:133:30
e@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:43:93
Hf/l.defer/c<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:45:491_

_Error: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.
createTransaction@resource://rester-at-kuehle-dot-me/data/site/scripts/services/data.js:411:31
self.getHistoryEntries/<@resource://rester-at-kuehle-dot-me/data/site/scripts/services/data.js:216:1
f/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:118:334
hf/this.$get</n.prototype.$eval@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:132:448
hf/this.$get</n.prototype.$digest@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:129:455
hf/this.$get</n.prototype.$evalAsync/<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:133:30
e@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:43:93
Hf/l.defer/c<@resource://rester-at-kuehle-dot-me/data/site/bower_components/angular/angular.min.js:45:491_

**Comment by frigus02** [comment]
@pwetosaurus I messed something up with the data storage and this update should have fixed it. In think in your case you still have some old and broken data. I will try to come up with a more robust solution in the next version.

In the mean time you should be able to delete the IndexedDB for RESTer from your file system. This shouldn't cause any data loss, because you don't have any data yet, right? To do this, go to your Firefox profile folder and then to "storage/default". For me the whole path looks like:

```
C:\Users\Jan\AppData\Roaming\Mozilla\Firefox\Profiles\qg9jgf9k.dev-edition-default\storage\default
```

Then delete the folder `resource+++rester-at-kuehle-dot-me` and reload RESTer in Firefox.

**Comment by pwetosaurus** [comment]
Thanks a lot, that was the correct solution!

For your information (and for users that could be suffering from this issue on Ubuntu, or some other GNU/Linux distributio), the RESTer module data are stored in `~/.mozilla/fiefox/{someHash.default}/storage/default/resource+++rester-at-kuehle-dot-me`
