### ISSUE TITLE
Page width issue when using long auth tokens

### ISSUE THREAD

**Issue by akupaka** [frigus02/RESTer#101]
Hi, @frigus02 !

It seems that some styles cause issues when very long auth tokens are used
You can see this screenshot https://imgur.com/kuQFADX
Unable to delete token, button is not visible, though TAB is useful here. And Send button shifted far away to the right.
~~If I'm not mistaken previous version didn't has this issue.~~ Nope it is there as well, in 3.10.00

Thanks!

**Comment by frigus02** [comment]
Thanks again for reporting 👍. I can reproduce this in both the new and the old version. I'm going to release a fix later today.

**Comment by frigus02** [comment]
I just uploaded version 3.11.1, which should fix the issue.

**Comment by akupaka** [comment]
Works just great! Thanks! =)
