### ISSUE TITLE
Post fields with json content

### ISSUE THREAD

**Issue by animalillo** [frigus02/RESTer#116]
I face the issue that when you happen to have a form field that holds json content the plugin detects it as a variable and it won't properly send the content.

This variable shows up as url encoded json in the variable list.

I have to work a lot with this kind of way to send json to the server and it's pretty annoying.
It would be cool to add a way to escape { and avoid the plugin to detect it as a variable this way, for example, it could ignore "\{" and send it as "{" to the server. Or some regex to detect if it has special chars like `:` or ` ,` or `"` inside and not use it as a variable if those are present.

The regex option would be awesome and it might be able to support variables inside this json fields, which would be neat!

Maybe this is related with #44 but I'm not sure.

Thanks for this awesome plugin! :D

**Comment by frigus02** [comment]
Thanks for reporting. I can reproduce at least parts of the bug.

I set the body to "Form" and add a field `json` with value `{"foo":{"bar":1}}`. Then:
- RESTer detects a variable. That's annoying and definitely a bug.
- If I leave the variable empty, RESTer sends `json={%22foo%22%3A{%22bar%22%3A1}}` to the server. This looks correct to me. Would you expect something else to be sent?

**Comment by animalillo** [comment]
that regex looks good to me.

I've had some trouble with the json fields that are part of the form, i'm not sure if the problem was due to the way our system process those, i'ts a bit picky about some things, but my request does not suceeds unless i enter the json inside a variable and fill that variable up.

But yeah, making a more specific regex to recognize variables  that avoids picking json as a variable would be awesome! that would even let you have json things that have variables inside, that'd be perfect!

**Comment by animalillo** [comment]
Maybe a more versatile regex could be ```{([^":,]).+}``` but i'll let that regex decision up to you

**Comment by frigus02** [comment]
That should be fixed in version 4.2.0, which should be available in the next days.
