### ISSUE TITLE
EXPORT REQUESTS gives you "Ups, something went wrong! e is undefined".

### ISSUE THREAD

**Issue by u023871** [frigus02/RESTer#127]
1st: I really like your RESTer plugin...

What I do not like is the issue in the EXPORT REQUESTS function...
* "Ups, something went wrong! e is undefined".
* No matter whether with or without history
* the issue persists for me for several... years I think meanwhile, at least 1 or 2, within different FX versions
* using version 4.0.0
* current FX 74
* no matter if with or without proxy configured

![4543A4B4-3C84-4739-A6D6-D4C7D840C19A_1_105_c](https://user-images.githubusercontent.com/15835306/78896276-8389e680-7a70-11ea-8c0a-d0fd1ac672db.jpeg)

Without that function I always have to start configuring my request from scratch after using a different Firefox on any new physical or virtual machine...

Would be cool if you tackle this!

Regards
eztup

**Comment by frigus02** [comment]
Hi @u023871, thanks for reporting. I'm not able to reproduce this. Could you please check if there are any messages in the web console (Ctrl+Shift+K)?

I assume a saved does not have a property RESTer expects it to have. I wrote some quick and dirty data validation script. Could you this in the console in a RESTer tab?

```js
(await Promise.all(Array.from(new Set((await browser.storage.local.get("requests")).requests.ids)).map(async id => (await browser.storage.local.get(`requests.e.${id}`))[`requests.e.${id}`]))).filter(r => typeof r.body !== 'string' || !r.collection || !r.title || !Array.isArray(r.headers) || r.headers.some(h => typeof h.name !== 'string' || typeof h.value !== 'string'))
```

**Comment by u023871** [comment]
Thanks for you quick response and sorry for my late one!

However, is there a different way than CTRL-SHIFT-K, as it does not work on my Macbook (at least nothing happens with the command and control keys instead of CTRL), unfortunately? I assume you meant a RESTer specific console and not the FX console you can open using F12 key?

I additionally tried to:
* create an environment, as there was none
* clean history

Both did not do it, unfortunately...

**Comment by frigus02** [comment]
Ah sorry, I should have been more clear. Yes, did mean the Firefox console (F12 or Cmd+Option+K on Mac).

**Comment by u023871** [comment]
Okay thanks, I made it. But do you know a way how to properly copy this JSON (?) array structure out of that FX console? I have 232 requests and don't want to expand them 1 by one... also need to wipe out all request credentials before attaching the output file here...

Regards

**Comment by frigus02** [comment]
Did you run the snippet from above and that printed an array with 232 requests? That's great, because it hopefully means we found the problem. On my side this snippet does not return anything.

![image](https://user-images.githubusercontent.com/3579251/79494805-84e08380-801b-11ea-806b-abc4c5134ae9.png)

Could you expand one of the requests copy it? One request should be enough information to for me to find what wrong 🤞.

**Comment by u023871** [comment]
Hi! Sorry, not allowed to work as much as I would like to, these days...

Yes, I ran your script, and it showed a very long result tree, including all my 232 requests.

Not sure whether one request will really help you... Created them over some time. Exported from 1 Firefox, imported maybe in a newer release, and this several times... But here 5 examples attached...

Brgds

[20200422 RESTer-127 request examples.txt](https://github.com/frigus02/RESTer/files/4515111/20200422.RESTer-127.request.examples.txt)

**Comment by frigus02** [comment]
Sorry for the delay. I didn't find the time to work on RESTer for the last days.

I just uploaded an update to RESTer (version 4.1.1). I managed to reproduce and fix a bug with the Postman export, which resulted in a very similar error message. This hopefully fixes the issue you're facing. I also made a change to show more details in the error dialog. So in case it doesn't fix your issue, the additional info if hopefully enough to track down the actual cause.

**Comment by u023871** [comment]
No worries, same for me... But you made my day :-) Export works fine now. After uninstalling RESTer and importing the file again, all requests were imported properly afaics.

Only thing is that after reinstalling RESTer all "Environment" settings are gone, as obvioulsy not part of the exported/imported data. Is this intended? Shall I open a new issue or feature request for that?

However: Thanks for your great help 👍 👍 👍

**Comment by frigus02** [comment]
Awesome. Thanks for reporting and being patient while I figured out what's wrong 🙂.

Exporting/importing environments is tracked in #95.
