### ISSUE TITLE
Build as part of release

### ISSUE THREAD

**Issue by pkoretic** [frigus02/RESTer#1303]
Hi @frigus02,

thanks for nice and simple extension.

It would be great to have it released also in the "binary" form as part of releases.
This way it would be installable also in cases where access to web stores is blocked (due to many other potentially vulnerable extensions)

e.g. [chrome-4.12.0.zip](https://github.com/user-attachments/files/18038548/chrome-4.12.0.zip)

Keep up the good work!

**Comment by frigus02** [comment]
Hi. Uploading the zip files should be doable. I'll see if I can upload the files for the latest release in the next days.

**Comment by frigus02** [comment]
Done for https://github.com/frigus02/RESTer/releases/tag/4.12.0 and will try to do as well for future releases.
