### ISSUE TITLE
Pressing Return/Enter in the URL input field should send the request

### ISSUE THREAD

**Issue by maffe** [frigus02/RESTer#14]
Currently nothing happens when pressing Return or Enter when the URL input field has focus, I expect it to send the request when using those buttons.

**Comment by frigus02** [comment]
Hi @maffe, thanks for your suggestion. Currently you can sent the request from any input field by pressing Ctrl+Enter.

Btw, you can see the available shortcuts by pressing ? (or clicking on "Shortcuts" on the bottom left corner.

I agree that just pressing Enter when you are in the URL field would be more intuitive. I'm not sure if you could press this accidently, though. I will test this locally. If I like it, I will include it in the next update.

**Comment by frigus02** [comment]
I just uploaded a new version 1.12.0, which contains this improvement.
