### ISSUE TITLE
OAuth v2 generate token name (Improvement suggestion)

### ISSUE THREAD

**Issue by kmontcalm** [frigus02/RESTer#140]
I defined a OAuth 2 profile to get the Authorization token (defined using the Environment variables)
When the token is created, the name is always "**Unknown (Environment: EnvName)**".

Since I'm working with different clients authentication tokens, is it possible to name the generated token something more descriptive ?

For example: "**OAuthTitle (Environmen: EnvName)**" ?
(OAuthTitle is the title we used when declaring the OAuth configuration)

It will me more easy to navigate through them.

Thanks to consider that for the next release.

KM

**Comment by frigus02** [comment]
Thanks for the suggestion. That's a good idea. It will be included in the next release.

**Comment by frigus02** [comment]
That should be included in version 4.2.0, which should be available in the next days.
