### ISSUE TITLE
Need to be able to delete many requests at once

### ISSUE THREAD

**Issue by dakaraphi** [frigus02/RESTer#144]
There seems to be no way to delete more than one request at a time.
I have many hundreds of requests shared by import/export.
If you make a mistake with import and put them in the wrong place, it seems there is no way to undo this.

**Comment by frigus02** [comment]
Hi @dakaraphi. Thanks for opening the issue. I agree with you. It would be great to have way of deleting multiple requests quickly.

Do you have an idea of a UI for that could look like?

**Comment by dakaraphi** [comment]
@frigus02 I somewhat desperately need this, so I would go with easiest to implement for now :-)

Maybe under Organize -> Cleanup
Add another button for delete requests.
Click the button would show full list where you can multi select items to delete.
Bonus would be add a filter field to the top so you can also pre-filter the list.

---
Another option.  If the UI would take long, would be to offer another option on import to do a `clean import` where all existing requests are removed and replaced with the import.  Then at least I could do an export, select and delete all the requests I want to delete and just re-import.

**Comment by frigus02** [comment]
Yeah, I'm thinking something under Organize would probably be the easiest thing.

---

Full disclosure: I probably won't be able to implement this in the next days.

If you need to something right now, you could reset RESTer and then import your saved requests. That would remove history and environments, though. It would work something like this:

1. Export requests
1. Edit export and remove from the JSON file what you don't need
1. Go to `about:debugging` in the browser
1. Under "This Firefox" find the RESTer extension and click on "Inspect"
1. That should bring you to a tab with the URL `about:devtools-toolbox?type=extension&id=rester%40kuehle.me`
1. Go go Storage -> Extension Storage -> moz-extension://xxx
1. Right-click on any entry and select "Delete All" (**warning:** this deletes everything)
1. You now have a fresh RESTer and you can import your previous export

**Comment by dakaraphi** [comment]
Thanks, that at least helps in the short term.

**Comment by frigus02** [comment]
I uploaded version 4.3.0, which has a basic dialog to delete multiple requests.

**Comment by dakaraphi** [comment]
Thanks! very helpful
