### ISSUE TITLE
Allow variable for OAuth2 token generation configuration

### ISSUE THREAD

**Issue by pmdhaussy** [frigus02/RESTer#16]
It could be great to allow env vars for token generation.
I use differents environments with each a dedicated OAuth server/configuration so I can't use this feature. :cry:

**Comment by frigus02** [comment]
Hi. I actually did plan to use variables for the OAuth tokens as well. Do I understand your proposal correctly?

You want to be able to use the environment variables in the OAuth2 client configuration (e.g. for the Client ID). So depending on the current environment you would generate a different token,

**Comment by pmdhaussy** [comment]
@frigu02 exactly. I need to set SSO server host & port, realm (part of the url) and client id according to current environment. It will be very useful.

**Comment by frigus02** [comment]
I agree. Currently I created multiple OAuth configurations for me (one for every environment). But using the envrionment in the OAuth configuration is a lot better.

**Comment by pmdhaussy** [comment]
I did that too.

My SSO server (Keycloak) allow to pass login & pwd in authorization code
request. I thinks it's a part of openid connect specification. But I didn't
found where to set my creds on RESTer.

**Comment by frigus02** [comment]
It looks like Keycloak can use the _Resource Owner Password Credentials_ flow (grant_type=password). This is not supported in RESTer yet. It isn't difficult to implement, though. So I might add this in the next update.

**Comment by pmdhaussy** [comment]
That's it!

**Comment by frigus02** [comment]
Version 1.13.0 is online now with both, support for the OAuth 2 Resource Owner Password Credentials flow and environment variables in the OAuth configuration. Please let me know, if this works for you.

**Comment by pmdhaussy** [comment]
Environment variables in the OAuth configuration works like a charm.
Can you please, add profile name in the generated token name?

**Comment by pmdhaussy** [comment]
Concerning OAuth2 authentication part, I don't find how can I set my login & pwd.
With `authorization code` and the new `Resource Owner Password Credentials` I should provide my creds to avoid redirecting to my SSO server.

**Comment by frigus02** [comment]
1. I think adding the profile name to the generated token is a good idea. This way you can use a environment variable in the name.

2. Here is my test configuration for the resource owner flow with Keycloak:

Configuration                               | Value
------------------------------------------- | -------------------------------------------
OAuth 2 Flow                                | Resource Owner Password Credentials
Access Token Request: Endpoint              | http://[server]/auth/realms/[realm]/protocol/openid-connect/token
Access Token Request: Client Authentication | HTTP Basic authentication
Client ID                                   | &lt;Receive from Keycloak admin page&gt;
Client Secret                               | &lt;Receive from Keycloak admin page&gt;

You can receive the client secret from the *Installation* tab of the client configuration in the Keycloak
admin console. Just select the *Format Option* "Keycloak OIDC JSON" and copy the value for of the *realm-public-key*.

When you generate a new token for this config, it will ask you for username and password. Then it will perform a request in the background to the server to get a token (without a redirect).

**Comment by frigus02** [comment]
Hi. Since today the version 1.14.0 is available, which adds the environment name to generated tokens. I found this looks nicer that putting an environment variable in the OAuth 2 configuration name.

I think everything in this issue is solved now, so I will close it. If I missed anything let me know and I can open it again.

**Comment by jgiovaresco** [comment]
It seems impossible to use an env variable to set the `Access Token Request Endpoint`. 

As you can see in the attached screenshot, I can't submit the form because of the error.

![capture d ecran 2016-09-27 a 15 20 03](https://cloud.githubusercontent.com/assets/4171593/18875443/10fbf214-84c6-11e6-8aab-e50ede1a99d5.png)

**Comment by pmdhaussy** [comment]
> It seems impossible to use an env variable to set the Access Token Request Endpoint. 

Same issue.

@frigus02 Could you disable the URL check if `Enable environment variables` is checked?

**Comment by frigus02** [comment]
Hey, good catch. I removed the URL validation for the field and uploaded a new version. Should be available in the next days.
