### ISSUE TITLE
HTML format in Dark Theme barely visible

### ISSUE THREAD

**Issue by sssanwar** [frigus02/RESTer#181]
Highlighting response in HTML format in Dark Theme won't change the font color. Since the font is in black and the background is dark it's very hard to see the text on screen. Version: 4.3.1

**Comment by frigus02** [comment]
Thanks for reporting. I don't seem to be able to reproduce that. For it looks like this:

![image](https://user-images.githubusercontent.com/3579251/94997078-a7059800-05a0-11eb-9b1a-541223da7f4f.png)

Would you mind sharing a screenshot?

**Comment by sssanwar** [comment]
Please see attached. For more info, I am using the extension in Firefox. From your screenshot, it appears that you're using the XML highlighting...
![Screen Shot 2020-10-04 at 12 33 10 pm](https://user-images.githubusercontent.com/24425684/95005040-ff8b7280-063e-11eb-9f6c-de0caa7515f7.png)

**Comment by frigus02** [comment]
Hm, interesting. It's not using syntax highlighting at all in your case. I wonder where the error comes from. Is that from RESTer? In any case, that should help me start searching. And I agree, the contrast gray background to black text here is not good.

**Comment by sssanwar** [comment]
The error comes from the Express server. Actually, I checked again and found that it does not matter whether it's returning 200 or 500 status. When the highlighting is HTML, the font will be set to black. Initially I thought the HTML returned by Express had the font set to black, but upon inspection there's no color CSS style in the returned HTML. In the screenshot below the response is pure JSON, yet the font is still black.
![Screen Shot 2020-10-04 at 9 41 35 pm](https://user-images.githubusercontent.com/24425684/95013246-ced12a80-068a-11eb-8cd8-1cb91ffa12be.png)

**Comment by frigus02** [comment]
Oh, I just had an idea. Do you have the checkbox next to "Preview" set, when you click on the 3 dot menu next to the response body?

![image](https://user-images.githubusercontent.com/3579251/95013601-424a4c00-0639-11eb-9c39-17de4f6c6bc2.png)

If set, this will render the response as HTML and that does not apply any styling. That's true.

I that should probably use a lighter background color (maybe even white) or change the text color to something lighter.
