### ISSUE TITLE
`Some variables have an empty value` notification not properly displayed

### ISSUE THREAD

**Issue by pmdhaussy** [frigus02/RESTer#20]
Even though all variables are set the message `Some variables have an empty value. ` is displayed.

![selection_052](https://cloud.githubusercontent.com/assets/3735794/19148107/7a7223b6-8bbb-11e6-8d4a-a22ed7478177.png)

Version: 1.15.0

**Comment by frigus02** [comment]
Hi. I can reproduce this and will upload a fix on the weekend. Thanks for reporting (and sorry for the bug).
