### ISSUE TITLE
Add PKCE support for oAuth2 authorization

### ISSUE THREAD

**Issue by fxjoos** [frigus02/RESTer#226]
First of all thank you for this great project.
 
It would be useful to have support for PKCE when using Oauth2/OpenId. In short, PKCE is a feature that allows to get rid of Client Secret in apps (only client id and a temporary "proof key").
Without this feature, when testing I cannot use the oauth client configuration of my JS app which use PKCE and I need to define a second oauth client configuration with a client id / client secret for dev/test purpose only. That means I am not strictly in the same "oauth context".

**Comment by frigus02** [comment]
Hi. That sounds like a good idea. I'm a bit short on time at the moment, so I probably won't be able to implement this anytime soon. But I'd be happy to review a PR if you would like to give it a go.

**Comment by frigus02** [comment]
Suddenly PKCE support got more important because I had a use case myself 🙂 

It's released in version 4.5.0. Should be in the extension stores in a few minutes/hours.
