### ISSUE TITLE
Request body gets truncated with presence of equal sign

### ISSUE THREAD

**Issue by raoulvolfonix** [frigus02/RESTer#23]
Using version 2.0.1
I try to paste in my request body a long JSON formatted string (5433 chars).
The content of the body is truncated to 2320 chars.

I check if this could just be a display issue and execute the request but I get a json parsing error from my server, so the body is really truncated.

**Comment by frigus02** [comment]
Hi, thanks for bringing this up. I will have a look at it in the next days.

**Comment by frigus02** [comment]
I just tried to reproduce the issue, but it works just fine for me. I posted a formatted JSON string with 29520 characters to [RequestBin](https://requestb.in) and everything came through.

To find out what's going on, would you mind testing the following things:
* Post my sample JSON string to your or the RequestBin server. I uploaded it here: http://pastebin.com/L5fU1bVR
* While pasting your not working JSON string into the request body and sending the request to your server, leave the web console (Ctrl+Shift+K) open and check for any errors.
* Send me a sample JSON, where you experience the issues with.

**Comment by raoulvolfonix** [comment]
I tried your query and it's fine.
The problem doesn't come from the query validity itself, but from copy-pasting it from a text editor into the text box of RESTer.
The string is cut in the middle of a base64 encoded parameter value.
I tried multiple times and it's always at the same place.
I checked my editor copy-pasting function and it's ok (copied from my editor and pasted in another one).

Here is the full parameter value:
"77b2d43c-60e6-4df7-8c92-27087d2797dc","signatureData":"QVhTobJVFUURTwlSyZaFq4xJDJ4akRLCi2NYAYEt3tG1jfzIUbFk6iQ8hPIFnb6BmplX70KKnrRY0dcZ3kjqTtZpUS1U1yTgDHB5EZizsmkzNA0Wr50tdBNiwsymTeKzvDwZaQJG6iHh9tds1qXwU5acH4nWZBiKakE+60EneSPGYYSpv717WoQS65O6nDP6slSasSOh4XuZwmSZysErWzHxtBc6Mu7vFepADDOwAi8k4AV2sl81p8oOCmbV30d4Pwn9bPjqrn0m8+BqWI9HTqbr7CP7wPCK6rq89Nm2fAwVsTcVVYwErvT/qLgkOJXcmjvtCPA186nvhlXC+pEEQg=="

In RESTer everything after "+pEEQg" (at the end of this string) is not pasted into the text box.

**Comment by frigus02** [comment]
Thanks a lot for the detailed report. I can reproduce it with your example. The 2 equal signs seem to be causing the issue. I can even reproduce it with something as simple as this:

```
abc==def
```

**Comment by denormalizer** [comment]
Just a note that a single equal sign causes this problem

**Comment by denormalizer** [comment]
A suggestion to change the title of the issue to (or similar):
"Parameter value gets truncated with presence of equal sign"

**Comment by frigus02** [comment]
Good point. The bug is already fixed by the way. I'm just waiting for Mozilla to review the update.

**Comment by denormalizer** [comment]
@frigus02 I'm not sure if it has been addressed in your fix yet, but I was not able to paste an equal sign in one of the parameter values (in form view)
> However. If I copy the missing data and paste it again in RESTer at the end of the first paste, it's OK and the request executes fine

**Comment by frigus02** [comment]
Hi @denormalizer. You are right, the form view still has the issue. Thanks for the hint. I will fix this in the next update.

**Comment by denormalizer** [comment]
Excellent! :)

**Comment by frigus02** [comment]
This should be fixed now. Version 2.2.0 is finally reviewed and available for Firefox and Chrome.
