### ISSUE TITLE
Problem to open saved Request

### ISSUE THREAD

**Issue by sabf81** [frigus02/RESTer#25]
I try your add-on and i like it.

I use Firefox 51.0.1 and if i try to save a request it is not possible for me to load the saved request again.
I try it with the shortcuts "cmd+o" and "cmd+p", enter the name of a saved request e.g. "GetUser" hit 'enter' and nothing happends.

**Comment by frigus02** [comment]
Hi. This sounds like an annoying bug. Can you go into more detail how you save the request? Saved requests should automatically appear in the left navigation bar.

When you click the Save button on the top right, and the request does not appear in the left navigation bar, would you mind opening the browser console (Ctrl+Shift+J) to check for any JavaScript errors?

**Comment by sabf81** [comment]
1. I execute a request
1.1 The request appears in the history list
2. Then i enter a collection/title
3. Press the save button
4. Nothings hapend

![bildschirmfoto 2017-02-14 um 07 59 50](https://cloud.githubusercontent.com/assets/13674691/22918694/d70530fa-f28b-11e6-9cdf-f18be0315bd7.png)

**Comment by frigus02** [comment]
Thanks for the detailed description, I think I see the issue now. Currently you actually need to enter a collection and title for the request separated by a "/". Try entering something like "Test / EmailConfing" and then save the request.

I also see now, that this is not really intuitive. I will think of something better for the next update.

I also want to add a little bit more information. RESTer saves 2 different things:
* **Requests:** These are just the requests with a Collection (you can use multiple "/" in the big input field to nest them) and a Title. They can include variables for placeholders. You have to save them manually and they don't save responses.
* **History:** These are the actual request + response sent to the server. Any variable, that was used when sending the request has been replaced here. So you actually see exactly what you sent. These are saved automatically whenever you send a request.

The "Quick Open" dialog (Ctrl+O / Ctrl+P) currently only shows saved requests. It does not show any items from the history. Do you think it would be useful to also search the full history in this dialog?

**Comment by sabf81** [comment]
Thank you for your hint. Now it works.
Perhaps you should use two separate input fields one for "Collection" and one for "Title".

> The "Quick Open" dialog (Ctrl+O / Ctrl+P) currently only shows saved requests. It does not show any items from the history. Do you think it would be useful to also search the full history in this dialog?
Yes that would be nice. 
What does the number means in the "Quick Open Result"-Window? That changes on each new char i enter.
![bildschirmfoto 2017-02-15 um 08 31 26](https://cloud.githubusercontent.com/assets/13674691/22964500/472387f6-f359-11e6-8012-7961842009be.png)

**Comment by frigus02** [comment]
That's good to hear. I will definitely improve the title input field. And I will also look into making the history searchable in the dialog. This might take a bit more time, though.

The big number in the dialog is just the search score of the entry. The higher the number, the better this entry matches your search. Results are ordered by this score. I thought it might by helpful to see what list is ordered by. But I might replace this number with something actually useful later :-)

**Comment by frigus02** [comment]
The UI to enter title and collection for a request has been improved in version 2.2.0. I will track the enhancement of the quick open dialog in another issue.
