### ISSUE TITLE
On Linux show curl command does not work with query string

### ISSUE THREAD

**Issue by mokilcde** [frigus02/RESTer#287]
Hi!

On Linux I create an query with a few parameter:
`http://localhost/test.php?a=b&path=login&b=a`

When I copy that to clipboard and try the command it will not work. I have to mask the `&` like that:
`http://localhost/test.php?a=b\&path=login\&b=a`
than it works

**Comment by frigus02** [comment]
Yeah, that's a good point. It would also be nice to support zsh, which apparently requires the `?` to be escaped, too.

**Comment by frigus02** [comment]
I submitted version 4.3.3 to the extension stores, which should fix the problem. It should be available in the next hours.

**Comment by mokilcde** [comment]
Thanks for that
