### ISSUE TITLE
Fails to load styles if no internet connection

### ISSUE THREAD

**Issue by TalasZh** [frigus02/RESTer#29]
Fails to load 

> https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic
> https://fonts.googleapis.com/css?family=Roboto+Mono:400,700

and I guess that causes interface dysfunction, i.e. cannot select Method type when creating new request.

**Comment by frigus02** [comment]
Hey. You are right, I didn't even notice this. Will try to fix this in the next update.

**Comment by frigus02** [comment]
New version is out, which should fix the issue.
