### ISSUE TITLE
Client secret should not be required in OAuth2

### ISSUE THREAD

**Issue by AdamZ** [frigus02/RESTer#31]
When creating an OAuth configuration, the form requires a value in the "Client Secret" field. However, not all clients have secrets (what the RFC calls "public clients"). Putting a space into the field works, however, it should be possible to just leave it blank as well.

**Comment by frigus02** [comment]
You are right. Fix will be included in the next update.

**Comment by frigus02** [comment]
New version is out, which includes an option for open OAuth clients.
