### ISSUE TITLE
Cookie auth support

### ISSUE THREAD

**Issue by Adrian-Cuellar** [frigus02/RESTer#32]
Hi, i'm trying to send a GET request against Drupal 8.2 but the plugin does not send the cookie that allows me to login, so I get 403 response.

If I  manually add the cookie to the header it works fine.
It would be nice to automatically add the cookie to the sent parameters.

I'm using Firefox for developers 54.0a2 (2017-04-02) (64-bit).

May thanks for the plugin, you've done a great job.

**Comment by frigus02** [comment]
Yep, this was also requested in #11. I want to add this feature, but I don't know when I find the time. It's certainly on the list, though.

**Comment by Francewhoa** [comment]
At Ubertus.org we would be happy to contribute testing and documentation for that feature

**Comment by frigus02** [comment]
Hi. That's nice to hear. Before I implement anything I would like to get your opinion. Will the following implementation help you?

I'm thinking about implementing the feature the same way as OAuth 2 is currently done. The flow would be like this:
1. One time you would configure a Drupal authentication with probably 3 parameters: **Login URL**, **Destination URL** and **Cookie Names**.
2. To get a new session cookie, you would start a new Drupal authentication. This will open the **Login URL** in a popup, allowing you to login. Once the page in the popup is redirected to **Destination URL** the popup closes. RESTer extracts the cookie and saves it.
3. To use the cookie in your request you need to select it (like you would select an OAuth token) before sending the request.

So RESTer would still not have an automatic cookie management (as that could be complex). It will just make it easier to get a session cookie and to inject it in requests.

**Comment by a-langer** [comment]
@frigus02 Hello.
Thank you for supporting this wonderful extension.
What should I do if the service does not use OAuth 2 authentication?
For example, to get cookies, the authorization form will be used:
```html
<form method="post" action="login">
	<input name="login" type="text">
	<input name="password"  type="password">
	<button type="submit" >Login</button>
</form>  
```  
In this case, you must send a POST request to the URL /login. At the moment RESTer does not support any form of authorization.

**Comment by frigus02** [comment]
Hi @a-langer. As you said currently only Basic and OAuth 2 authentication is supported.

Unfortunately the normal login you see on websites using cookies is not standardized. So it's a bit harder to support it properly. One simple POST request might not be enough depending on how the website implements the login flow. Also cookie names vary across sites.

I think a login flow as I described above would work with most sites. RESTer would store the cookie for future requests and allow for easily generating new cookies. Would this flow fit your needs?

**Comment by NobleUplift** [comment]
[HttpRequester](https://github.com/tommut/HttpRequester) automatically uses cookies of the website you're querying against but I don't know if that's possible with WebExtensions.

**Comment by a-langer** [comment]
@frigus02 I would like to be able to log in manually at this stage:
> This will open the Login URL in a popup, allowing you to login. 

At this stage of the algorithm, is it possible to save cookies (not using OAuth 2)?

**Comment by a-langer** [comment]
@NobleUplift yes, also uses cookies [RESTED](https://addons.mozilla.org/ru/firefox/addon/rested/) .
These additions are not "WebExtensions"?

**Comment by frigus02** [comment]
Thanks for your feedback. I think by default a request from an extension should send the cookie for the target website. For RESTer however I explicitly avoid this currently. I really wanted that the request you see is the actual request, which is sent.

I now realize that there is value in just letting the browser send a normal request, including the normal cookies. I might add a setting to RESTer, which will allow you to switch between clean requests and normal browser requests.

In addition I think the special cookie authentication could be useful. This would store the cookies the same way that the OAuth authentication currently stores the access token. It would allow you to store cookie of different users and switch between them during requests.

I try to take a closer look at this tomorrow.

**Comment by frigus02** [comment]
Alright, I just uploaded version 3.4.0, which comes with cookie support. I added 2 things:

1.  In the settings you can now select a request mode. If you select "Browser Requests", RESTer will send the request as the browser normally would (**including** cookies).

2.  There is a new authorization option called "Cookie". It works similar to the OAuth 2 option. You configure it once with start and end url. Then you can generate and store as many cookies as you like and easily switch between.

    Note: I couldn't think of a way to extract a meaningful name from cookies, so all stored cookie tokens are called "Unknown" for now. I plan to fix this later.

I like this to far. Let me know if this works for you.

**Comment by a-langer** [comment]
@frigus02 Authorization through "Browser Requests" works fine. Thank you.

**Comment by frigus02** [comment]
Thanks for the feedback. I'm going to close this now. If more options are needed feel free to reopen or create a new issue.
