### ISSUE TITLE
Can't upload multiple files

### ISSUE THREAD

**Issue by vensires** [frigus02/RESTer#33]
I am trying to upload multiple files to a webservice built with PHP. When POSTing data with the name `files[]` the `[` and `]` characters get encoded in the request and instead of receiving an array with `files` as key (as is the process in PHP) I receive an array with one file keyed as _files%5B%5D_.

**Comment by frigus02** [comment]
Thanks for bringing this up. Will fix this issue in the next update.

**Comment by frigus02** [comment]
New version is out, which should fix the issue.
