### ISSUE TITLE
Variables don't work properly in Form mode

### ISSUE THREAD

**Issue by denormalizer** [frigus02/RESTer#35]
How to reproduce:

* Create new request
* Change to *Form* mode
* Set content type to: `application/x-www-form-urlencoded` (as per usual)
* Enable variables for request
* Add arbitrary parameter `param1`
* Set value of `param1` to `{param1-value}`
* Check *Variables* tab, no param1-value
* In *Body* tab, change from `Form` mode to `Plain`

    `param1=%7Bparam1-value%7D`

So the issues seems to be that variables are url encoded.

The solution might be to urlencode only after the variables have been substituted

**Comment by frigus02** [comment]
Damn, you are right. I missed that during the last fixes for the form input. Thanks a lot for reporting. I will fix this in the next update.

**Comment by frigus02** [comment]
I just uploaded version 2.5.0, which includes the fix. Review times were slow the last few updates, though. So it might take 1-2 weeks to be public.

**Comment by frigus02** [comment]
The version is public now.

**Comment by denormalizer** [comment]
Can confirm it is working
