### ISSUE TITLE
Clicking HTTP method from dropdown menu does not work

### ISSUE THREAD

**Issue by denormalizer** [frigus02/RESTer#36]
How to replicate:

* Create new request
* Click on method input box (a drop down menu appears)
* Select REST (edit: HTTP) method. Method input box is empty

Expect method to be selected and input box to be filled.

There seems to cases where it does work, although it seems intermittent.

**Comment by frigus02** [comment]
Hey, thanks for reporting.

Can you explain "Select REST method" in more detail?
* There is no "REST" value in the dropdown, so I wonder: do you type it in first?
* Or do you select just any of the suggested methods? If so, are there some methods more likely to work then others?
* How do you select the method: mouse click or keyboard arrow keys and enter?

And last: which browser (Chrome/Firefox) and version do you use?

**Comment by denormalizer** [comment]
* Sorry I meant HTTP methods: GET, POST, PUSH etc
* It usually happens when selecting a suggested method, prior to typing
* Method is selected using mouse click
* I'm using Firefox 54

I can't seem to be able to replicate it at the moment though.

**Comment by frigus02** [comment]
Thanks for the clearification. It's possible, that the latest update fixed something. It was approved for Firefox on the 20th. Let's see if you can reproduce the issue again. If not I will close the issue in a couple of days.

**Comment by maffe** [comment]
I’m using RESTer 2.5.0 in Firefox 54.0.1. I think I have found the problem.

Steps to reproduce:
* Click in an empty field (HTTP method, header name …) to open the drop down menu
* Press the mouse button to select a suggestion. If you release the button fast enough, the field is filled with the selected suggestion. If you release the button too slowly (which happens easily), the field stays empty.

**Comment by frigus02** [comment]
Hi, good catch. I can reproduce it this way. And you are right, this can happen easily. I'm currently uploading another bugfix. I think I'll include this one as well.

**Comment by frigus02** [comment]
I just uploaded a new version with the bugfix. It should be available within the next week.

**Comment by frigus02** [comment]
The new version is finally live.
