### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by David-Maisonave** [frigus02/RESTer#360]
Great Plugin!  This is the best REST extension of tried so far.
A few minor issues with the GUI.

#1 URL Parameter button is confusing.
The button is an arrow, and it's not immediately obvious what the arrow does. Even after clicking the arrow, it just drops two sets of fields (Name & Value), which doesn't explain what it's a name and value for.
I recommend changing the button to "URL Param", and optionally add a up & down arrow at the end of the name.  Or if you want to keep the minimal looking GUI, you could add a hover popup text which could explain the arrow button.

#2 Environment option has add button hidden away at lower bottom corner.
When I first clicked the Environment option, I thought there was something wrong, because I mainly saw a blank page.  I finally notice the small add button only after viewing it using a narrow window. 
On a wide screen, this small button is so far removed from the main GUI real-estate, that it's very easy to miss.
I recommend moving the button to the top part of the Environment window.

#3 Environment 3-dot option button shows empty small square.
When clicking on the 3-dot Environment option, the window darkens, and a small empty white square is displayed.
After creating  an environmental variable, then the white square contains the variable.
I recommend adding window header, or just disabling the 3-dot button if there are no variables to display.

**Comment by frigus02** [comment]
Hi David, thanks for the nice words and the suggestions. I agree with all 3 them.

I can't promise I come around to implementing them soon, but will try. If you would like to give it a go, I'd also be happy to review pull requests for them.

**Comment by frigus02** [comment]
Fixed in 4.7.0. Should be available in the next hours.
