### ISSUE TITLE
Missing Tab "Variables" on FireFox 54.0

### ISSUE THREAD

**Issue by sabf81** [frigus02/RESTer#37]
The tab "Variables" disappeared after the Firefox update to 54.0 

So the only way to edit the varialbes is to enter them directly, if they are in the url.
![notabvariables](https://user-images.githubusercontent.com/13674691/27779964-59fd16d8-5fc6-11e7-9d78-1b9dd3fdd1fc.png)

**Comment by frigus02** [comment]
Thanks for the report. I honestly don't know why I didn't see this earlier. I will upload a bugfix later today.

Until then, here's the workaround: If you switch pages (say to the history and back), or if you resize the browser window enough, the tab will appear.

**Comment by gruentee** [comment]
I can confirm this bug, using Firefox 54.0 on Linux here.

**Comment by frigus02** [comment]
Thanks for confirming. And sorry again for the issue. A new version is already uploaded and currently under review. I hope it will be public within the next few days.

**Comment by frigus02** [comment]
The new version is finally live.
