### ISSUE TITLE
Counterintuitive removal of the question mark in URLs

### ISSUE THREAD

**Issue by maffe** [frigus02/RESTer#38]
Steps to reproduce:
* Enter URL `https://localhost/foo?bar=baz`
* Select `bar=baz`
* Press Ctrl+X

Expected result:
* `bar=baz` is removed
* Clipboard contains `bar=baz`

Actual result:
* `?bar=baz` is removed
* Clipboard contains `bar=baz`

I often use the cut command (Ctrl+X) followed by insert (Ctrl+V) instead of copy (Ctrl+C) to have a visual feedback, but in this case after inserting the cut part the URL is different from the original.

Using RESTer 2.5.0 in Firefox 54.0.1.

**Comment by frigus02** [comment]
Hi, thanks for reporting. I can reproduce the issue and will make sure to fix this in the next update.

**Comment by frigus02** [comment]
That's fixed in the newest update 3.0.0.
