### ISSUE TITLE
Selecting a saved auth token deletes Cookie headers

### ISSUE THREAD

**Issue by Roy-Orbison** [frigus02/RESTer#395]
1. Fill out the HEADERS tab of a new request with random data.
2. Include a `Cookie` header.
3. Select (or create & select) a new token in the AUTHORIZATION tab.
4. Return to the HEADERS tab.
5. The `Cookie` header will have disappeared.

**Comment by frigus02** [comment]
Hi @Roy-Orbison, thanks for reporting. This is definitely not how I wanted this to behave. I'll try to fix this in the next days.

**Comment by frigus02** [comment]
I uploaded a new version. Should be available in the next few hours.

**Comment by Roy-Orbison** [comment]
Thanks! Fast turnaround. It wasn't a deal-breaker, I only had to copy the cookie value, select the auth, and paste the cookie back.
