### ISSUE TITLE
Headers are ignored (Chrome)

### ISSUE THREAD

**Issue by brumartins** [frigus02/RESTer#399]
Hi,

I just noticed today that Headers not more taken into account when doing an HTTP request. Authorization, Accept... are not applied.

It seems broken only on Chrome (91.0.4472.101) though, works fine on Firefox extension.

Thank you in advance for your help! 

Here some console error : 
```
Error in event handler: TypeError: Error in invocation of webRequestInternal.eventHandled(string eventName, string
subEventName, string requestId, integer webViewInstanceId, optional webRequest.BlockingResponse response): Error at 
parameter 'response': Error at property 'requestHeaders': Error at index 10: Unexpected property: 'flag'.
at subEventCallback (extensions::webRequestEvent:82:28)
```

**Comment by frigus02** [comment]
Oops. Thanks for reporting. That was caused by the last update. I should add some automated tests for Chrome to catch these issues.

Anyway, I'm working on a fix. Should be released soon.

**Comment by brumartins** [comment]
Thanks a lot, that was quick! 😀 Firefox extension is now in version 4.5.2, but still 4.5.1 on Google store, I guess I'll have to wait for a few more hours. Have a nice day!

**Comment by frigus02** [comment]
Hm yeah. It still says "pending review" for 4.5.2 in the Chrome developer dashboard. Usually it's super quick. I imagine it shouldn't take too much longer. Fingers crossed 🙂

**Comment by brumartins** [comment]
Chrome extension is now updated, works perfect, thanks!!

**Comment by frigus02** [comment]
Great! Thanks for confirming.
