### ISSUE TITLE
Display response body as a web page

### ISSUE THREAD

**Issue by raoulvolfonix** [frigus02/RESTer#4]
This is not an issue but a nice-to-have request:
Would it be possible to display the response body as a web page when it contains HTML ?

**Comment by frigus02** [comment]
This sounds like a good feature. I can just think of one question to clearify first:

- How should this handle linked resources inside of the HTML like styles, images, scripts?

Do you have a suggestion?

**Comment by raoulvolfonix** [comment]
I don't know, I guess just display the result as-is, or provide options for the user to choose depending on the content type ?

**Comment by frigus02** [comment]
I added a basic version of this for HTML. Most dangerous tags like `<style>` or `<script>` will be stripped before being rendered.

Something similar might be interesting for languages like markdown or maybe templates like handlebars. So maybe I will enhance this functionality in the future.
