### ISSUE TITLE
Cursor jumps to end when changing URL structure

### ISSUE THREAD

**Issue by maffe** [frigus02/RESTer#40]
Steps to reproduce:
* Enter URL `https://localhost/a?b`
* Select `?`
* Replace the `?` with a `/` (or change it back to `?`)

Then the cursor jumps to the end of the URL, making editing harder than it should be.

**Comment by frigus02** [comment]
Thanks for reporting. This is clearly a bug. It's caused by the same thing like #38, which is fixed in master. I plan to release an update on the weekend.

**Comment by frigus02** [comment]
That's fixed in the newest update 3.0.0.
