### ISSUE TITLE
Long number wrong when display json result as "Pretty Print"

### ISSUE THREAD

**Issue by kmontcalm** [frigus02/RESTer#401]
I have a command that return me a long number in a json record.
Example:
`{"items":[{"longnumber":55871516310040211}],"first":{"$ref":"https://myurl/api/gettest"}}`

When display as "Pretty, it returns this:
```
{
    "items": [
        {
            "longnumber": 55871516310040210
        }
    ],
    "first": {
        "$ref": "https://myurl/api/gettest"
    }
}
```
The last digit of the number return "0" instead of "1".

Seems to be tiny bug.

Thanks to look at this.

KM.

**Comment by frigus02** [comment]
Oh no. Thanks for reporting. RESTer uses `JSON.stringify(JSON.parse(body), null, 4)` for pretty printing. The number is too large to fit into  `Number` apparently and there is a rounding error.

![image](https://user-images.githubusercontent.com/3579251/121591253-2b15f680-ca31-11eb-9a6e-198582036ec1.png)

That's probably not an easy fix. We will have to find another way of pretty printing JSON.

**Comment by kmontcalm** [comment]
I'm working with Oracle databases and the numbers can by big up to 20 digits.

**Comment by frigus02** [comment]
That sounds like a perfectly valid use case.

Maybe something like https://www.npmjs.com/package/json-bigint can help. I'm going to have a closer look in the next days.

**Comment by frigus02** [comment]
I just uploaded version 4.6.0, which fixes this. JSON formatting is a bit slower now, but that should only be noticeable with a very large JSON string. Definitely worth it, I think.
