### ISSUE TITLE
Extension don't initialize on Firefox 56 (developer edition)

### ISSUE THREAD

**Issue by Leuloch** [frigus02/RESTer#41]
My environment is:
Ubuntu 16.04
64bit
Firefox  56.0b12 (64-bit)

When I click to open de extension, just show up a blank page.

**Comment by frigus02** [comment]
Hi. Thanks for reporting this issue. Could you please provide the following additional information:

* RESTer version: You should be able to find this on the addons page (Firefox Menu > Addons > RESTer > More). I'm assuming it's 3.0.0?
* Error log from the web console: Open the extension, which only shows a blank page. Then open the web console (Ctrl+Shift+K). Then reload the blank page to see if any error messages are displayed.

**Comment by braedon** [comment]
I've got the same issue - same Firefox version (but Ubuntu 17.04), RESTer 3.0.0.

console errors:
```
XML Parsing Error: not well-formed Location: jar:file:///home/braedon/.mozilla/firefox/ktkd1nhk.default/extensions/rester@kuehle.me.xpi!/site/elements/rester-app.html Line Number 1, Column 737:  rester-app.html:1:737
<script> source URI is not allowed in this document: “jar:file:///home/braedon/.mozilla/firefox/ktkd1nhk.default/extensions/rester@kuehle.me.xpi!/site/elements/rester-app.js”.  index.html:1
```

**Comment by Leuloch** [comment]
I'm am using: 
Firefox 57.0b1 (64-bit)
Rester 3.0.0

console error:
```
XML Parsing Error: not well-formed
Location: jar:file:///home/ednei/.mozilla/firefox/bjdh6fu4.dev-edition-default/extensions/rester@kuehle.me.xpi!/site/elements/rester-app.html
Line Number 1, Column 737:
rester-app.html:1:737
<script> source URI is not allowed in this document: “jar:file:///home/ednei/.mozilla/firefox/bjdh6fu4.dev-edition-default/extensions/rester@kuehle.me.xpi!/site/elements/rester-app.js”.
index.html:1
```

**Comment by frigus02** [comment]
Thank you both for the info. I believe I had this issue with Firefox 55 myself. But never for 56 or 57. I have no idea what's happening here. An URI like in the log ("jar:file://...") should never be requested.

Anyway, I will try to fix this on the weekend.

**Comment by frigus02** [comment]
I just uploaded version 3.1.0, which should fix the issue.

Mozilla very recently changed the review process to make this a lot faster. I believe the version is already live.

**Comment by chenjr0719** [comment]
This issue seems to appear again with:
Ubuntu 17.04
FireFox 57.0b11
Rester 3.2.0

When I revert to version 3.1.0, it can work properly.

The log from console:
```

XML Parsing Error: not well-formed
Location: jar:file:///home/jacob/.mozilla/firefox/p3jrsu2o.default/extensions/rester@kuehle.me.xpi!/site/elements/rester-app.html
Line Number 1, Column 752:
rester-app.html:1:752
<script> source URI is not allowed in this document: “jar:file:///home/jacob/.mozilla/firefox/p3jrsu2o.default/extensions/rester@kuehle.me.xpi!/site/elements/rester-app.js”.
index.html:1
```

**Comment by frigus02** [comment]
Thanks for the heads up. I disabled version 3.2.0 for now while I'm investigating the cause. It's really weird, since this does not happen on my Windows machine. I probably need to setup some automated test on a Ubuntu VM so this does not happen again.

**Comment by chenjr0719** [comment]
It's a good idea. Maybe integrate this project with [Travis CI](https://travis-ci.org/) can help you to run the automated test easier.

**Comment by frigus02** [comment]
Ok, version 3.2.1 is out and working.

I will think about how to automate the testing now. Travis CI was also what I had in mind. I'm just not sure how to perform the actual test. I really need to install RESTer as an extension and then open it. Maybe [web-ext](https://github.com/mozilla/web-ext) can help me here.
