### ISSUE TITLE
Variable placeholders and json content...

### ISSUE THREAD

**Issue by BrunoJunior** [frigus02/RESTer#44]
I would like to use your REST client but I have a problem.
To communicate with my PrestaShop module, I use the PrestaShop API.
To make some tests I POST requests via a SETC client.
When I tried to send my data, my body request is modified because I have JSON content, and RESTer detects variable …

Exemple :
`<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<xlpos_action>
	<action>TesterConnexion</action>
	<parameters>{"test":true}</parameters>
</xlpos_action>
</prestashop>`
And I have a ""test":true" variable but it is not …

**Comment by frigus02** [comment]
Hi. I can reproduce the issue. This is a bug. Unused variables (where you don't enter any value) should not change the request. I will fix this in the next update.

**Comment by frigus02** [comment]
Version 3.5.0 is already out, which includes the fix. Please let me know if this does not work.
