### ISSUE TITLE
Add feature to remove cookies

### ISSUE THREAD

**Issue by rain1** [frigus02/RESTer#443]
I thought it would be nice convenience feature to have checkbox "remove cookies" below submit button that when checked no cookies would be sent. 

For example when I need to test authentication I dont want to send cookie because then cookie authentication gets done on server side instead of authentication that I need to test. Deleting cookies manually is annoying. Checkbox would also remind you of cookies so that you would not spend time trying to figure out what is going on in authentication only to find out that it was done using cookie.
I would even implement it so that  this checkbox would remove cookies from request itself but not from browser storage if it is possible that way.  Then that checkbox would not log me out from other tabs.

To me sending cookie even seems like bug because from that kind of tool I'd expect it only sends what I tell it to send and nothing else.

**Comment by frigus02** [comment]
Hi @rain1. There is an option for this but it's quite hard to find:

1. Use the cog icon in the sidebar to go to the settings page
1. Change "Request Mode" to "Clean Requests"

I struggled with what the default should be here. I can see reasons for both. Either way, it might be nice to make this option easier to discover. Maybe there is a nice way of adding the option somewhere near the "Send" button.
