### ISSUE TITLE
GET query parameters too long

### ISSUE THREAD

**Issue by dongshimou** [frigus02/RESTer#45]
like 
```
token=xxxx(200 character)
```

when i input a long paramater.

The whole interface is stretched。

<img width="1471" alt="qq20171127-151330 2x" src="https://user-images.githubusercontent.com/9100799/33254960-512e9d72-d386-11e7-9283-ea8d065c7648.png">

**Comment by frigus02** [comment]
Thanks for the report. I can reproduce the issue. This will be fixed in the next update.

**Comment by frigus02** [comment]
Version 3.5.1 is out, which includes the bugfix. If this does not work for you, feel free to reopen the issue.
