### ISSUE TITLE
Does not use all available space for the response window

### ISSUE THREAD

**Issue by GeoffreyGamaya** [frigus02/RESTer#48]
When the browser is in full screen the response window does not use all available space.
So you have a big empty unused space in the bottom

 ![like this](https://image.noelshack.com/fichiers/2018/02/3/1515593504-capture.png?raw=true)

It's very annoying when you need to read a long text file response.

But great work ! 👍

**Comment by frigus02** [comment]
Hi @GeoffreyGamaya. Sorry for the late response. I accidentally disabled GitHub notifications and didn't see your issue.

There is an option in the "three-dot-menu" of the response body called "Full Size". When activated, the body field will have the size of the response. The downside is, that very large responses can slow down the browser if this option is activated.

Is this option enough in your case?

**Comment by GeoffreyGamaya** [comment]
> There is an option in the "three-dot-menu" of the response body called "Full Size". When activated, the body field will have the size of the response.

It was stupid of me not to see it. It's working well even with a big json (several Mo). Another solution can be to have a responsive window to adapt to the size of the browser, but I don't know how difficult it is to do it.

Thank you for your answer, your tool is even better than postman.

**Comment by frigus02** [comment]
Thanks for the nice words. Adapting it to the size of the browser was what I initially planned to do. But then I postponed the idea because I didn't want to deal with all possible edge cases. I might pick this up again in the future, though.
