### ISSUE TITLE
Saving a request removes the response

### ISSUE THREAD

**Issue by Bilge** [frigus02/RESTer#49]
A somewhat minor but nevertheless annoying usability issue is that when saving a request, if there is a response currently displayed, it is removed. I don't see any good reason to do this from a usability perspective. If it's not a major technical challenge, I think it should be avoided.

**Comment by frigus02** [comment]
Hi @Bilge. Sorry for the late response. I accidentally disabled GitHub notifications and didn't see your issue.

This is annoying, I agree. It was just simpler to implement this way. But it should definitely be fixed. Thanks for bringing this to my attention.

**Comment by frigus02** [comment]
Alright. Version 3.6.0 is out (or should be in the next minutes), which should fix this.
