### ISSUE TITLE
By default add the request-header Accept with the value */* if it is not present in the request

### ISSUE THREAD

**Issue by raoulvolfonix** [frigus02/RESTer#5]
With a client sending requests to a JBoss AS 7 server, I have a problem when posting a request without the Accept header. It returns an Error 400:Bad Request with a JBoss Error: "JBWEB000120: The request sent by the client was syntactically incorrect.".
When I add the Accept header with a correct value (in my case: "application/json") or "\*/\*", I get a response 200:OK and the data I am expecting.
I don't know if it would be a correct behavior, but it would be nice to add this header with a default value if it is not specified in the request.

**Comment by frigus02** [comment]
Good point. Currently RESTer tries to strip all default headers like Accept or User-Agent. But this is probably better hidden behind an opt-in setting.

I guess I can implement this in the next days.

**Comment by raoulvolfonix** [comment]
Opt-in setting is a good idea
