### ISSUE TITLE
RESTler 3.5.1 disabled by Firefox Developer Edition 59.0b3 (64bit) on Linux

### ISSUE THREAD

**Issue by tsdh** [frigus02/RESTer#50]
I just updated my Firefox Developer Edition from 59.0b2 to 59.0b3, and after a restart it informed my that it just disabled an add-on which would be incompatible with Firefox Developer Edition.  That add-on is RESTler 3.5.1 which, I think, worked fine with 59.0b2 (I actually haven't used it for some weeks, but at least it didn't get disabled).

When I try to enable it again, it immediately switches back to disabled state.

**Comment by tsdh** [comment]
Gosh, now I could enable it again, and it seems to stay up and running.  So this might have been a temporary hiccup.  Feel free to close this issue if you want.  I'll reopen it in case it happens again.

**Comment by frigus02** [comment]
Hi. Thanks for reporting this. It's good that it's working again. I'll reopen this, if I hear again about this issue.

**Comment by tsdh** [comment]
Gosh, now I could enable it again, and it seems to stay up and running.  So this might have been a temporary hiccup.  Feel free to close this issue if you want.  I'll reopen it in case it happens again.
