### ISSUE TITLE
Body is not copiable

### ISSUE THREAD

**Issue by TerkiKerel** [frigus02/RESTer#53]
Hi,

When I copy a text from body is copies an empty string. Can you please fix this issue?

thank you

**Comment by frigus02** [comment]
Hi @TerkiKerel, thanks for reporting the issue. I had a quick look, but was unable to reproduce it. Could you please share:
- Your browser (Firefox/Chrome) and browser version
- Your operating system (sometimes this makes a difference)
- The version of RESTer (you can see it by clicking on the tiny "About" link in the bottom left corner of RESTer)

**Comment by TerkiKerel** [comment]
Here a screenshot from body block of extension:
![1](https://user-images.githubusercontent.com/30633816/36218815-a52db86c-11c6-11e8-8097-f724b2faf622.png)

I am using:
Ubuntu 16.04 64 bit
Firefox 58.0.1 (64-bit)
Extension version: 3.5.1 & 3.7.1 (both have same issue)

I only copy the text from screenshot I add on this message. I paste it to any text editor. It only pastes a space or nothing. I try to copy with CTRL+C or by right clicking with mouse.

**Comment by TerkiKerel** [comment]
I think I found the reason. See the screenshot:

![2](https://user-images.githubusercontent.com/30633816/36219273-dce68260-11c7-11e8-9f94-b7a375c8aa23.png)

"hello" and "hi" text are inside different "span" html objects. so when I copy them browser sucks...

**Comment by frigus02** [comment]
Thanks for tracking this down. The `<span>` elements should be fine. They are necessary for the syntax highlighting.

I tested this today on Ubuntu but was still not able to reproduce the issue. For the body RESTer uses the Ace editor. Would you mind going to https://ace.c9.io/ and try copying from the editor on this page. I wonder if this is a general issue of the editor or specifically to RESTer.

**Comment by TerkiKerel** [comment]
![3](https://user-images.githubusercontent.com/30633816/36267960-57255ace-1286-11e8-9c4a-d5832d3a9357.png)
Yes the bug depends on Ace editor. I copy the text to gedit (text editor). The character is something different as you can see on the screenshot.

**Comment by TerkiKerel** [comment]
Now I open a new firefox profile. Now It works. I think another extension or config makes this happen.

Thanks for your interest :)

**Comment by frigus02** [comment]
You're welcome. Also thanks a lot for your effort in finding the issue.

**Comment by TerkiKerel** [comment]
Only for information:
I solve the problem by setting "dom.event.clipboardevents.enabled" confgi as true.
