### ISSUE TITLE
Open in current tab

### ISSUE THREAD

**Issue by sirideain** [frigus02/RESTer#54]
Please add an option to open in the current tab rather than always opening in a new tab. I am using Firefox Multi-Account Containers, so I would like to be able to open a new tab in a specific container and then open RESTer directly in that tab.

**Comment by frigus02** [comment]
Hey @sirideain, I like the suggestions. Thanks for bringing this up. I will look into it in the next days.

**Comment by frigus02** [comment]
With version 3.8.0 (released a few minutes ago) RESTer opens in the current tab when you are on the new tab page. This might not work when an extension modified the new tab page.

Please let me know if this is helpful for you.

**Comment by sirideain** [comment]
This fits my need. Thank you.
