### ISSUE TITLE
Variables cannot contains some special characters

### ISSUE THREAD

**Issue by Timmy93** [frigus02/RESTer#573]
## Environment
- **Browser version**: Firefox 96.0.1 (64 bit)
- **OS**: Windows 10
- **Software**: browser addon (https://addons.mozilla.org/en-US/firefox/addon/rester/) 
- **Version** 4.8.0

## Scenario
I am testing a custom application that requires a token to successfully authenticate.
The request has has the following Content-Type: `application/x-www-form-urlencoded`
I have to send the following base64 token: `VTierV8gyBGFD5eLbr5ezpb/QGUeVvVeBFz8YieasQGktPBH4/F3KYl15pcajVGb5OD5A/memUS/PuN07k1vbeJLFLethBq5Bj2LvwdUoHWRHhd/vBSNPf/atv41AfRq3X+LuCIz75bROPY8l9A5jxJfiPPpJMbt54qh9CKDHX1vYFOi+9n1tyLrz1l1lDbB6BF+xIVk6sjtmcRMCMWFVifxYPfkEW2P2NDVPsyZDPC9xKDzJUfC6eF2xJBs1L2IO7nK1lGp3haJrvgY54HuuM+6h99uFvTRMu+J5d3WRpbnfhYOqzHMaZr4n44G/+oDPScyBysz5i7n6KZrp6V2zQ==`

## What's going wrong?
When I insert the token directly in the form field I successfully login 
(Received value: `VTierV8gyBGFD5eLbr5ezpb/QGUeVvVeBFz8YieasQGktPBH4/F3KYl15pcajVGb5OD5A/memUS/PuN07k1vbeJLFLethBq5Bj2LvwdUoHWRHhd/vBSNPf/atv41AfRq3X+LuCIz75bROPY8l9A5jxJfiPPpJMbt54qh9CKDHX1vYFOi+9n1tyLrz1l1lDbB6BF+xIVk6sjtmcRMCMWFVifxYPfkEW2P2NDVPsyZDPC9xKDzJUfC6eF2xJBs1L2IO7nK1lGp3haJrvgY54HuuM+6h99uFvTRMu+J5d3WRpbnfhYOqzHMaZr4n44G/+oDPScyBysz5i7n6KZrp6V2zQ==`)
![immagine](https://user-images.githubusercontent.com/10899430/149671550-7184a62b-a0d4-4ae8-8ea8-757807c5f5bf.png)

Insted when I try to store this token in a variable or in an ENV variable, some characters are deleted (like `+` and `=`) and then the authentication fails. 
(Received value: `VTierV8gyBGFD5eLbr5ezpb/QGUeVvVeBFz8YieasQGktPBH4/F3KYl15pcajVGb5OD5A/memUS/PuN07k1vbeJLFLethBq5Bj2LvwdUoHWRHhd/vBSNPf/atv41AfRq3XLuCIz75bROPY8l9A5jxJfiPPpJMbt54qh9CKDHX1vYFOi9n1tyLrz1l1lDbB6BFxIVk6sjtmcRMCMWFVifxYPfkEW2P2NDVPsyZDPC9xKDzJUfC6eF2xJBs1L2IO7nK1lGp3haJrvgY54HuuM6h99uFvTRMuJ5d3WRpbnfhYOqzHMaZr4n44G/oDPScyBysz5i7n6KZrp6V2zQ`)
![immagine](https://user-images.githubusercontent.com/10899430/149671528-ba5658e0-97dc-4791-9635-2c47490a6c59.png)

## Expected behaviour
The token is sent correctly either using direct value or using the variable

**Comment by frigus02** [comment]
Thanks for reporting. I can easily reproduce. This doesn't just affect form input.

Currently variables replacement in the body happens after any kind of encoding. That means in your example the request sent to the server contains:

```
req=searchMaterial&psw=VTierV8gyBGFD5eLbr5ezpb/QGUeVvVeBFz8YieasQGktPBH4/F3KYl15pcajVGb5OD5A/memUS/PuN07k1vbeJLFLethBq5Bj2LvwdUoHWRHhd/vBSNPf/atv41AfRq3X+LuCIz75bROPY8l9A5jxJfiPPpJMbt54qh9CKDHX1vYFOi+9n1tyLrz1l1lDbB6BF+xIVk6sjtmcRMCMWFVifxYPfkEW2P2NDVPsyZDPC9xKDzJUfC6eF2xJBs1L2IO7nK1lGp3haJrvgY54HuuM+6h99uFvTRMu+J5d3WRpbnfhYOqzHMaZr4n44G/+oDPScyBysz5i7n6KZrp6V2zQ==
```

And after decoding this on the server some characters are indeed missing.

**Comment by frigus02** [comment]
I uploaded version 4.8.1, which fixes this for form inputs. Update should be available within the next few hours.

**Comment by Timmy93** [comment]
Thank you, I confirm it's working correctly.
