### ISSUE TITLE
Last version broke my variables

### ISSUE THREAD

**Issue by garro95** [frigus02/RESTer#583]
Due to #581, I cannot store anymore my variables like `$env.host = http://myserv.myenv.local:8082` because `:` and `/`are encoded
Maybe encoding could be made optional?

**Comment by frigus02** [comment]
Oh no. I wanted make encoding happen only for the body. But then forgot to do that.

**Comment by frigus02** [comment]
I uploaded a new version, which only encodes variable in the request body. Should be available for update in the next hours.
