### ISSUE TITLE
Feature: support Nan

### ISSUE THREAD

**Issue by Jihadist** [frigus02/RESTer#593]
Is it possible to add support for NaN? It's commonly used extension but rester doesn't support it and pretty print doesn't work if reply contains NaN.

**Comment by frigus02** [comment]
To clarify: I noticed there may be a slightly confusing error message involving NaN:

https://github.com/frigus02/RESTer/blob/279abb7bf52ea335ac3f1e997360930e09eb2772/src/site/elements/data/scripts/format-json.js#L58

Is that what you're seeing? Or do you actuallz have some JSON with NaN in it, e.g.:

```json
{ "value": NaN }
```

**Comment by Jihadist** [comment]
Yep. It's for json formatting. I have JSON with NaN as your example.

**Comment by frigus02** [comment]
Thanks for confirming. Supporting NaN does sound sensible to me.

**Comment by frigus02** [comment]
I just released version 4.9.0, which supports `NaN`. Should be available as an update in the next few hours.

**Comment by Jihadist** [comment]
Thanx
