### ISSUE TITLE
This is not an issue ...

### ISSUE THREAD

**Issue by dxxvi** [frigus02/RESTer#6]
... how can I start it in Firefox?

**Comment by pwetosaurus** [comment]
There is a new button on the right of your address bar (with default configuration) with two arrows over a globe.

Simply click on it.

**Comment by frigus02** [comment]
Hi. As pwetosaurus pointed out, there should be an icon the address bar. If this is not the case, have a look in the menu or in the firefox customize view.

You can also go to the following URL manually: resource://rester-at-kuehle-dot-me/data/site/index.html
