### ISSUE TITLE
Environment variables do not work in Body

### ISSUE THREAD

**Issue by ps-spark** [frigus02/RESTer#61]
Unfortunately the environment variables do not work in the Body, only in Header. There should be a clear notification in the Environment menu that the variables do not work overall until this bug is fixed.

<img width="1061" alt="rester_body_env_bug" src="https://user-images.githubusercontent.com/19947879/38973970-71e2d730-43a8-11e8-9cec-5181e5e9f17a.png">

**Comment by frigus02** [comment]
Thanks for the report. I can reproduce the issue. Will have a closer look in the next days.

**Comment by frigus02** [comment]
Version 3.8.1 is out now and includes a fix 🙂

**Comment by ps-spark** [comment]
Thank you very for the quick fix. It works well.
