### ISSUE TITLE
using a # in a value truncates the sent request

### ISSUE THREAD

**Issue by aturbati** [frigus02/RESTer#628]
I've noticed that if you use a # in a value (in the name-value part), then the request is truncated up to that point. The only way I found out to sent a value with a # is to click on the "arrow" near the URL to "Toggle URL params" (so the name-value list is no longer visible) and to manually replace the # with a %23 in the URL itself. If I try to replace in the name-value part the # with a %23, immediatelly after I write the "3" it is automatically converted in a # so it seems not to be possible to modify there that character

**Comment by frigus02** [comment]
Thanks for reporting. For some reason RESTer doesn't encode values in URL params unless the name/value contains a `=` or `&`. I can't remember why I did that and apparently I also didn't write that down anywhere.

I think it would be safer to always encode query params. Lets try that.
