### ISSUE TITLE
Authorization with username and empty password not possible

### ISSUE THREAD

**Issue by Ndhb478** [frigus02/RESTer#65]
Hi,

we have a devolopment environment on which we use simple authorization with username and empty passwords. RESTer doesn't allow such a config at the moment (Generate new token -> Basic).

It would be great, if you "fix" this in a later version.

Thanks!

**Comment by frigus02** [comment]
Hi. Thanks for the suggestion. Again I'm being too restrictive, because I didn't think that an empty password would be useful 🙂. It's definitely something I can fix.

Just to clarify, how would the generated header look like? Would it be like this?

```
// User:  "admin"
// Pass:  ""
// Token: base64("admin:") --> "YWRtaW46"
Authorization: Basic YWRtaW46
```

**Comment by Ndhb478** [comment]
Hi frigus02!

Thanks for your quick response. Header is correct!

**Comment by frigus02** [comment]
I just uploaded version 3.9.0, which fixes this issue. It should be available as an update within the next hours.
