### ISSUE TITLE
Content type suggestion doesn’t recognize types with charset parameter

### ISSUE THREAD

**Issue by maffe** [frigus02/RESTer#66]
When a content type header including a charset parameter is present, it is suggested to set the header to the same value without a charset parameter. In this case the suggestion is superfluous.
![rester](https://user-images.githubusercontent.com/515302/42806986-f1f1b354-89af-11e8-9647-301f8d300628.png)

**Comment by frigus02** [comment]
I just uploaded version 3.9.0, which fixes this issue. It should be available as an update within the next hours.
