### ISSUE TITLE
Open final url in new tab

### ISSUE THREAD

**Issue by keremcankabadayi** [frigus02/RESTer#674]
Hi there, I'm also using this [JSON viewer](https://addons.mozilla.org/en-US/firefox/addon/json-beautifier-editor/), especially for auto epoch time converter. 

![image](https://user-images.githubusercontent.com/23381187/170092396-94a784ee-5f99-404c-b059-5e992539ac6e.png)

I need to open new tab my `GET` requests to use this JSON viewer. So, it would be good to open final url.
Currently, my workaround is clicking `Show Curl Command` to see final url included variables and selecting text, right click `Open Link In New Tab`

For example:
`{$env.gw}/api/{id}?anotherId={someFlag}&anotherThing={var1}&var2={var3}`
final url = `localhost:9000/api/123?anotherId=12&anotherThing=435&var2=154`

my suggestion is that `Open Link In New Tab` final url here
![image](https://user-images.githubusercontent.com/23381187/170093808-3e6da2bc-646c-4814-8aa3-cd760e1b2aa1.png)

**Comment by keremcankabadayi** [comment]
@frigus02 added changes. deploy and let's see changes

**Comment by frigus02** [comment]
Thanks @keremcankabadayi. I uploaded a new version. It should be available in the next few hours.
