### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by Buzut** [frigus02/RESTer#7]
I have the impression that placeholder doesn't work in FF 46.0.1
![capture-d ecran-2016-05-20-a-11 07 41](https://cloud.githubusercontent.com/assets/6450536/15422939/5230b05a-1e7b-11e6-996e-f01e43311003.jpg)
![capture d ecran 2016-05-20 a 11 08 06](https://cloud.githubusercontent.com/assets/6450536/15422942/559dd614-1e7b-11e6-9e31-6a7bf7a2e84f.png)
![capture d ecran 2016-05-20 a 11 10 34](https://cloud.githubusercontent.com/assets/6450536/15422978/8e3e71f4-1e7b-11e6-9747-a47f32858d9e.png)

**Comment by Buzut** [comment]
wooow, sorry my bad, I hadn't noticed I had to turn variables on per request to make this work. Problem solved.

Man this is definitelly the best REST extension EVER on Firefox. I have tried a lot, but yours is way better (graphically and functionally). Keep up the good work 👍

**Comment by frigus02** [comment]
Hi @Buzut, you are right. Currently you need to manually turn variables on for each request. The reason is, that I didn't want to accidently replace stuff. I see now, however, that this is not the most straightforward solution. I will think of automatically enable variables if possible.

**Comment by Buzut** [comment]
It could be more user friendly but it's ok though. I'll be glad to test your improvements.
