### ISSUE TITLE
Allow empty client_secret for OAuth2 password grant type

### ISSUE THREAD

**Issue by crmky** [frigus02/RESTer#71]
Currently user must type a non-empty string for client_secret, but in my use case the client_secret requires an empty string, and server always return 401.

**Comment by crmky** [comment]
Found workaround for that. I can modify stroage.js and modify "clientSecret" to empty string.

**Comment by frigus02** [comment]
Hi @crmky, there is an option "None (public client)" in the "Access Token Request: Client Authentication" dropdown. It hides the client secret input field:

![image](https://user-images.githubusercontent.com/3579251/43537915-7ddcc732-95b8-11e8-9e8e-7dad79246df4.png)

Is this what you want?

Looking at this now, I can see that this is not obvious. Just leaving the client secret empty would probably be easier 🙂.

**Comment by crmky** [comment]
It's not exactly the same. The server (Pivotal CloudFoundry, https://docs.cloudfoundry.org/api/uaa/version/4.19.0/index.html#password-grant) requires `client_secret` present, but set to empty value.

If I choose "public client", RESTer will ask for user name and password first (which is expected),

![first](https://user-images.githubusercontent.com/1175644/43641377-042beb62-9756-11e8-90fb-b0fdef13aaab.png)

then it populate another dialog (unexpected), I have to specify client_id as user name, empty string as password to login. My guess is RESTer didn't send `client_secret` at all, so server returns 403, and pop-up browser authentication dialog.

![second](https://user-images.githubusercontent.com/1175644/43641321-c74184f0-9755-11e8-9ffe-1de7125a478a.png)

**Comment by frigus02** [comment]
Oh right. That's clearly a bug in RESTer. I will have a closer look. Also sorry for the late response.

**Comment by frigus02** [comment]
Fixed in version 3.9.1. Sorry it took me so long to release this.
