### ISSUE TITLE
Broken in FF 46.0.1

### ISSUE THREAD

**Issue by Bilge** [frigus02/RESTer#8]
![broken](https://cloud.githubusercontent.com/assets/470626/15505009/8336b8d4-21b9-11e6-8fe8-e7bf1641e771.png)

**Comment by frigus02** [comment]
Hi. Thanks for reporting and sorry for the issue. On a fresh install I can not reproduce this bug. Could you post potential error messages from the console in the developer tools (F12), please?

**Comment by mann-ed** [comment]
@frigus02 

Looks like it's in lin-inspections.js on my machine. Granted this could just be my error. My screen looks the same.
line 49
 add ({message, check, fixLabel, onFix, onDismiss=angular.noop}, $scope) {

SyntaxError: missing : after property id
add ({message, check, fixLabel, onFix, onDismiss=angular.noop}, $scope) {
---------------------------------------------------------------^

I will remove the plugin and install it again, see if it changes anything.

Error: [$injector:unpr] http://errors.angularjs.org/1.5.5/$injector/unpr?p0=%24lintInspectionsProvider%20%3C-%20%24lintInspections%20%3C-%20RequestCtrl
O/<@file:///C:/Users/manne1/Documents/rester/data/site/bower_components/angular/angular.min.js:6:412

**Comment by frigus02** [comment]
Thanks, @mann-ed. Found it. I will upload an update today.

**Comment by mann-ed** [comment]
@frigus02 

Thanks for the quick response. I'll be looking forward to the fix.

**Comment by frigus02** [comment]
I just uploaded version 1.9.1, which fixes the issue. Normally the review takes about 1 day, so you can expect the auto-update tomorrow. If you need it now, you might be able to install it manually from here:

https://addons.mozilla.org/de/firefox/addon/rester/versions/1.9.1

**Comment by mann-ed** [comment]
I got the update this AM. Everything is working fine in my environment. @Bilge are things working for you?

@frigus02  thanks for the quick fix.
