### ISSUE TITLE
Ruby on Rails backend API with CSRF protection 

### ISSUE THREAD

**Issue by rrevi** [frigus02/RESTer#84]
Hello,

I am trying to use RESTer with a Rails API which has CSRF protection. When I attempt to make POST/PATCH/etc. type of requests, the corresponding X-CSRF-Token header isn't being sent in the request. 

Has anyone used RESTer with a Rails API with CSRF protection before? (or with any server backend API with CSRF protection enabled)

I am essentially wondering if RESTer doesn't support Rail's CSRF protection or am I just missing a configuration in my POST/PATCH/etc. type of requests.

Thanks for any help,
Raf

**Comment by frigus02** [comment]
Hi Raf, have you tried calling another service (e.g. https://requestbin.co) with the header? Just to rule out the server.

I'm going to try and reproduce this in the evening. Which browser and browser version are you using?

**Comment by rrevi** [comment]
> Hi Raf, have you tried calling another service (e.g. https://requestbin.co) with the header? Just to rule out the server.
> > I'm going to try and reproduce this in the evening. Which browser and browser version are you using?

I am on RESTer 3.9.1 on Firefox 60.4.0esr (64-bit).

I have not tried calling another service with the header, since you generally get the X-CSRF-Token from the server from your previous request.

**Comment by rrevi** [comment]
Closing the issue, since it is not an actual issue with RESTer but rather...

Essentially, for a Rails API you need to just allow requests from all origins and for those HTTP methods which the API domain allows (which should also turn off the 'Can't verify CSRF token authenticity.' error). For more, read https://medium.com/@Nicholson85/handling-cors-issues-in-your-rails-api-120dfbcb8a24 and https://til.hashrocket.com/posts/4d7f12b213-rails-5-api-and-cors 

Thanks for the prompt reply!

**Comment by frigus02** [comment]
Thanks for the clarification.

To add to this: RESTer will send the `X-CSRF-Token` header if you add it manually to the request. However RESTer does not automatically extract the token from a previous response.

As far as I can see the header is not standardized, either. So adding support specifically for this header to RESTer is probably not a good idea. However a feature similar to Postman's `pm.environment.set()`, which lets you write code snippets to extract variables from a response would be great. That may come in the future.
