### ISSUE TITLE
Custom ORIGIN header

### ISSUE THREAD

**Issue by emvidi** [frigus02/RESTer#86]
Hi there, 
     just found your plugin for Firefox and I like it very much, but I would like to set the Origin header myself, its that possible? In the headers menu the Origin header seems to be missing. Thks

**Comment by frigus02** [comment]
Hi @emvidi, the headers in the dropdown are just a list of more or less common headers. You can enter any header name you want, though, e.g. `My-Custom-Header`. I just tested and `Origin` works for me. I just entered it like this and received it on my server:

![image](https://user-images.githubusercontent.com/3579251/53767249-1ef37400-3ecd-11e9-83e8-c88e8a4b01ad.png)

Let me know if that doesn't work for you. It may be a bug then.

**Comment by emvidi** [comment]
Thanks @frigus02, I assumed the headers were hard coded in the menu, didn't thought of changing the header name. I tried it and it works. Thanks for your work on this awesome plugin.
:)
