### ISSUE TITLE
add and save headers to the existing headers list

### ISSUE THREAD

**Issue by emvidi** [frigus02/RESTer#87]
Hi there,
  is it possible to add headers to the header list, like ORIGIN, ACCESS-CONTROL-REQUEST-METHOD, etc...? I mean to add them myself to the list and just select them when I need one. Thks

**Comment by frigus02** [comment]
The list of headers is currently hard coded. It's quite easy to extend, though. If you are interested in more standard headers, I can add them in the next release. Looking at [HTTP headers on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) there are actually quite a few we could add:

- `Access-Control-Request-Method`
- `Access-Control-Request-Headers`
- `Origin`
- `Early-Data`
- `DPR`
- `Save-Data`
- `Viewport-Width`
- `Width`
- `Vary`
- `Keep-Alive`
- `DNT`
- `Content-Language`
- `Forwarded`
- `Upgrade-Insecure-Requests`

Would those be enough for you or are you interested in adding custom headers to the list?

**Comment by emvidi** [comment]
Hi @frigus02,

    I am happy with the first 3 as hardcoded, which I need for CORS, but I think it will be practical as well to be able to add some custom headers to the list. Maybe a plus sign on the right next to the custom header to add to the list (if it is not very complicated to do). Thank you.

**Comment by frigus02** [comment]
I released version 3.10.0 with the above headers added. I also added another issue to track adding custom headers, because that's a bit more work.
