### ISSUE TITLE
Showing count as NaN

### ISSUE THREAD

**Issue by ntrjpatel** [frigus02/RESTer#96]
While doing cleanup history when I have no history the count selector bar shows NaN while displaying count as 0.
See the attached screenshot for reference.

Steps to reproduce - 
1) Install RESTer for chrome
2) Go to Organize menu
3) Click on Cleanup History under Cleanup section
4) Try to select the count from "Delete oldest entries" bar and it shows NaN if you have no any history available.

![Screenshot from 2019-05-02 15-11-25](https://user-images.githubusercontent.com/6889622/57067911-e36aff80-6ced-11e9-807a-803c305bf150.png)

**Comment by frigus02** [comment]
Thanks for the hint and detailed report. I can reproduce the issue. I'm going to try and fix this in the next update 🙂.
