### ISSUE TITLE
Make auth tokens available between restarts

### ISSUE THREAD

**Issue by akupaka** [frigus02/RESTer#97]
Hi there!

First of all I'd like to thank contributors for such a nice tool! I use RESTer as Firefox extension and find it very useful!

What makes me upset is that Authorization tokens are not saved between restarts.
That is when I generate new custom token it appears in Authorization tab and I can choose it for a request. If I save the request this token is saved in Headers. But if I close RESTer and start it again there is no any tokens in Authorization tab available.

Is it possible to save them for example like environment variables or something similar?

Thanks!

**Comment by frigus02** [comment]
Hi @akupaka, thanks for reporting this. Auth tokens are definitely supposed to be saved across restarts. This is a bug, which I can reproduce. I'm going to fix this in the next update.

**Comment by frigus02** [comment]
I uploaded version 3.11.0, which fixes this problem. It should be available for download in the next few hours.

**Comment by akupaka** [comment]
It works! Thanks!
